[package]
name = "midi-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.2.1", default-features = false }
windows = { version = "0.39.0", features = ["Win32_Media_Audio"] }
